### ISSUE TITLE
Deployment fails when FleetWise has been used in the account previously.

### ISSUE THREAD

**Issue by mttwise** [aws-samples/cdk-aws-iotfleetwise#44]
When deploying, the CreateSignalCatalog operation fails if a Signal Catalog was previously created when using FleetWise.

The following error is thrown by the custom resource:

```bash
5:02:08 PM | CREATE_FAILED        | AWS::CloudFormation::CustomResource | SignalCatalogCatalogResourceFC71CDF4
Received response status [FAILED] from custom resource. Message returned: Error: An error occurred (LimitExceededException) when calling th
e CreateSignalCatalog operation: AWS IoT FleetWise couldn't create the signal catalog. You can associate up to 1 signal catalog with an acc
ount for an AWS Region.

Logs: /aws/lambda/integ-stack-SingletonLambdasignalcataloghandlerone-XXXXXXXXX

at invokeUserFunction (/var/task/framework.js:2:6)
at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
at async onEvent (/var/task/framework.js:1:369)
at async Runtime.handler (/var/task/cfn-response.js:1:1573) (RequestId: bfbc6c74-0577-434c-b902-60c92abfccc1)
```

The following is observed in the CloudWatch Logs:
```Bash
[ERROR] LimitExceededException: An error occurred (LimitExceededException) when calling the CreateSignalCatalog operation: AWS IoT FleetWise couldn't create the signal catalog. You can associate up to 1 signal catalog with an account for an AWS Region.
Traceback (most recent call last):
  File "/var/task/signalcataloghandler.py", line 11, in on_event
    return on_create(event)
  File "/var/task/signalcataloghandler.py", line 22, in on_create
    response = client.create_signal_catalog(
  File "/opt/python/botocore/client.py", line 535, in _api_call
    return self._make_api_call(operation_name, kwargs)
  File "/opt/python/botocore/client.py", line 980, in _make_api_call
    raise error_class(parsed_response, operation_name)
```

**Comment by rmncardoso** [comment]
There is a Service Quota limit for Signal Catalog as follows: 
Number of signal catalogs for each account in an AWS Region = 1
https://docs.aws.amazon.com/general/latest/gr/iotfleetwise.html

and this is a hard limit. cannot be changed.

**Comment by mttwise** [comment]
Thanks for the info @rmncardoso. Closing this issue as this is a service issue and cannot be overcome by the sample.
